/** Canonical cities and degrees for searchable multi-selects. */

export const IP_REF_CITIES = [
  ['Mumbai', 'Maharashtra'],
  ['Delhi', 'Delhi'],
  ['Bengaluru', 'Karnataka'],
  ['Hyderabad', 'Telangana'],
  ['Chennai', 'Tamil Nadu'],
  ['Kolkata', 'West Bengal'],
  ['Pune', 'Maharashtra'],
  ['Ahmedabad', 'Gujarat'],
  ['Jaipur', 'Rajasthan'],
  ['Surat', 'Gujarat'],
  ['Lucknow', 'Uttar Pradesh'],
  ['Kanpur', 'Uttar Pradesh'],
  ['Nagpur', 'Maharashtra'],
  ['Indore', 'Madhya Pradesh'],
  ['Bhopal', 'Madhya Pradesh'],
  ['Visakhapatnam', 'Andhra Pradesh'],
  ['Vadodara', 'Gujarat'],
  ['Coimbatore', 'Tamil Nadu'],
  ['Kochi', 'Kerala'],
  ['Chandigarh', 'Chandigarh'],
  ['Patna', 'Bihar'],
  ['Agra', 'Uttar Pradesh'],
  ['Nashik', 'Maharashtra'],
  ['Vijayawada', 'Andhra Pradesh'],
  ['Madurai', 'Tamil Nadu'],
  ['Rajkot', 'Gujarat'],
  ['Jodhpur', 'Rajasthan'],
  ['Ranchi', 'Jharkhand'],
  ['Raipur', 'Chhattisgarh'],
  ['Amritsar', 'Punjab'],
  ['Dehradun', 'Uttarakhand'],
  ['Guwahati', 'Assam'],
  ['Bhubaneswar', 'Odisha'],
  ['Mysuru', 'Karnataka'],
  ['Thiruvananthapuram', 'Kerala'],
  ['Mangaluru', 'Karnataka'],
  ['Aurangabad (Chhatrapati Sambhajinagar)', 'Maharashtra'],
  ['Salem', 'Tamil Nadu'],
  ['Tiruchirappalli', 'Tamil Nadu'],
  ['Tiruppur', 'Tamil Nadu'],
  ['Udaipur', 'Rajasthan'],
  ['Kota', 'Rajasthan'],
  ['Ajmer', 'Rajasthan'],
  ['Prayagraj', 'Uttar Pradesh'],
  ['Varanasi', 'Uttar Pradesh'],
  ['Meerut', 'Uttar Pradesh'],
  ['Ludhiana', 'Punjab'],
  ['Jalandhar', 'Punjab'],
  ['Jammu', 'Jammu & Kashmir'],
  ['Srinagar', 'Jammu & Kashmir'],
  ['Goa / Panaji', 'Goa'],
  ['Gwalior', 'Madhya Pradesh'],
  ['Jabalpur', 'Madhya Pradesh'],
  ['Hubballi-Dharwad', 'Karnataka'],
  ['Belagavi', 'Karnataka'],
  ['Kozhikode', 'Kerala'],
  ['Kannur', 'Kerala'],
  ['Thrissur', 'Kerala'],
  ['Nellore', 'Andhra Pradesh'],
  ['Tirupati', 'Andhra Pradesh'],
  ['Kakinada', 'Andhra Pradesh'],
  ['Warangal', 'Telangana'],
  ['Vijayapura', 'Karnataka'],
  ['Kolhapur', 'Maharashtra'],
  ['Solapur', 'Maharashtra'],
  ['Bareilly', 'Uttar Pradesh'],
  ['Aligarh', 'Uttar Pradesh'],
  ['Moradabad', 'Uttar Pradesh'],
  ['Gorakhpur', 'Uttar Pradesh'],
  ['Durgapur', 'West Bengal'],
  ['Siliguri', 'West Bengal'],
  ['Asansol', 'West Bengal'],
  ['Cuttack', 'Odisha'],
  ['Rourkela', 'Odisha'],
  ['Puducherry', 'Puducherry'],
  ['Remote', 'Work mode'],
  ['Remote / Hybrid', 'Work mode'],
];

export const IP_REF_DEGREES = [
  [1, '10th', '10th Pass'],
  [2, '12th', '12th Pass / Higher Secondary'],
  [3, 'ITI', 'Industrial Training Institute'],
  [4, 'Diploma', 'Diploma'],
  [5, 'Polytechnic', 'Diploma in Engineering'],
  [6, 'BA', 'Bachelor of Arts'],
  [7, 'B.Com', 'Bachelor of Commerce'],
  [8, 'B.Sc', 'Bachelor of Science'],
  [9, 'BBA', 'Bachelor of Business Administration'],
  [10, 'BCA', 'Bachelor of Computer Applications'],
  [11, 'B.Tech', 'Bachelor of Technology'],
  [12, 'B.E.', 'Bachelor of Engineering'],
  [13, 'B.Arch', 'Bachelor of Architecture'],
  [14, 'B.Des', 'Bachelor of Design'],
  [15, 'B.Pharm', 'Bachelor of Pharmacy'],
  [16, 'LLB', 'Bachelor of Laws'],
  [17, 'B.Ed', 'Bachelor of Education'],
  [18, 'MBBS', 'Bachelor of Medicine & Bachelor of Surgery'],
  [19, 'BDS', 'Bachelor of Dental Surgery'],
  [20, 'BAMS', 'Bachelor of Ayurvedic Medicine & Bachelor of Surgery'],
  [21, 'BHMS', 'Bachelor of Homeopathic Medicine & Surgery'],
  [22, 'BVSc', 'Bachelor of Veterinary Science'],
  [23, 'MA', 'Master of Arts'],
  [24, 'M.Com', 'Master of Commerce'],
  [25, 'M.Sc', 'Master of Science'],
  [26, 'MBA', 'Master of Business Administration'],
  [27, 'MCA', 'Master of Computer Applications'],
  [28, 'M.Tech', 'Master of Technology'],
  [29, 'M.E.', 'Master of Engineering'],
  [30, 'LLM', 'Master of Laws'],
  [31, 'M.Ed', 'Master of Education'],
  [32, 'M.Pharm', 'Master of Pharmacy'],
  [33, 'M.Arch', 'Master of Architecture'],
  [34, 'PG Diploma', 'Post Graduate Diploma'],
  [35, 'CA', 'Chartered Accountant'],
  [36, 'CS', 'Company Secretary'],
  [37, 'CMA', 'Cost & Management Accountant'],
  [38, 'CFA', 'Chartered Financial Analyst'],
  [39, 'PhD', 'Doctorate / Doctor of Philosophy'],
  [40, 'Any Graduate', "Any Bachelor's Degree"],
  [41, 'Any PG', 'Any Post Graduate Degree'],
  [42, 'Any Professional Degree', 'Any Professional Degree'],
  [43, 'Any Diploma', 'Any Diploma'],
];
